name: Skylab New York
favicon: null
layout_spectrum: 0.302405220689252
typography_spectrum: 0.8694891596678644
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.025072767166420817
  lightness: 0.3500273663084954
  saturation: 0.9473510435782373
  rhythmicContrast: 0.876470735296607
purpose: []
